//!MOST OF THIS WAS GENERATED BY AI ADD YOUR CONTENT HERE
import {
  CheckCircle,
  Award,
  Heart,
  Building,
  Users,
  Phone,
  Mail,
  ArrowRight,
  Star,
  Zap,
  Leaf,
  Shield,
} from "lucide-react"

export const services = [
  {
    id: "residential",
    title: "Residential Construction",
    icon: "Home",
    description: "Crafting dream homes with precision and passion.",
    features: [
      "Custom home design",
      "Energy-efficient builds",
      "Smart home integration",
    ],
    benefits: [
      "Personalized living spaces",
      "Increased property value",
      "Modern comfort",
    ],
    expertise: 95,
    projects: 250,
    testimonial: {
      text: "ConstructCo turned our vision into reality. Our new home exceeds all expectations!",
      author: "Emily & David Thompson",
    },
    rating: 4.9,
    completionTime: "6-12 months",
    priceRange: "$300k - $1.5M",
  },
  {
    id: "luxury_homes",
    title: "Luxury Homes",
    icon: "Crown",
    description:
      "Building opulent residences that epitomize luxury and elegance.",
    features: ["High-end finishes", "Premium materials", "Exclusive designs"],
    benefits: ["Unmatched luxury", "Exclusive living", "High resale value"],
    expertise: 98,
    projects: 150,
    testimonial: {
      text: "Our luxury home is the envy of the neighborhood. Superb craftsmanship!",
      author: "Michael & Sarah Johnson",
    },
    rating: 4.95,
    completionTime: "8-14 months",
    priceRange: "$1M - $5M",
  },
  {
    id: "eco_friendly",
    title: "Eco-Friendly Homes",
    icon: "Leaf",
    description: "Sustainable construction for a greener future.",
    features: ["Solar panels", "Recycled materials", "Water-saving fixtures"],
    benefits: [
      "Lower energy bills",
      "Environmental conservation",
      "Healthy living environment",
    ],
    expertise: 90,
    projects: 180,
    testimonial: {
      text: "We love our eco-friendly home. It's beautiful and sustainable!",
      author: "James & Linda Brown",
    },
    rating: 4.8,
    completionTime: "5-10 months",
    priceRange: "$250k - $1.2M",
  },
  {
    id: "smart_homes",
    title: "Smart Homes",
    icon: "Wifi",
    description: "Integrating the latest technology for intelligent living.",
    features: ["Automated systems", "Voice control", "Home security"],
    benefits: ["Convenience", "Enhanced security", "Energy efficiency"],
    expertise: 93,
    projects: 200,
    testimonial: {
      text: "Our smart home is incredibly convenient and secure. Highly recommend!",
      author: "Karen & John Miller",
    },
    rating: 4.85,
    completionTime: "7-12 months",
    priceRange: "$300k - $1.3M",
  },
  {
    id: "renovations",
    title: "Home Renovations",
    icon: "Wrench",
    description: "Transforming spaces to meet modern needs and aesthetics.",
    features: ["Kitchen remodeling", "Bathroom upgrades", "Basement finishing"],
    benefits: [
      "Updated look",
      "Increased home value",
      "Improved functionality",
    ],
    expertise: 92,
    projects: 300,
    testimonial: {
      text: "Our renovation project was seamless and the results are stunning!",
      author: "Anna & David Wilson",
    },
    rating: 4.9,
    completionTime: "2-6 months",
    priceRange: "$50k - $500k",
  },
  {
    id: "additions",
    title: "Home Additions",
    icon: "PlusSquare",
    description: "Expanding living spaces with seamless integration.",
    features: ["Room extensions", "Second stories", "In-law suites"],
    benefits: [
      "More space",
      "Increased property value",
      "Enhanced functionality",
    ],
    expertise: 91,
    projects: 120,
    testimonial: {
      text: "The addition to our home looks like it was always there. Amazing work!",
      author: "Rebecca & Sam Lewis",
    },
    rating: 4.87,
    completionTime: "4-8 months",
    priceRange: "$100k - $800k",
  },
  {
    id: "outdoor_spaces",
    title: "Outdoor Living Spaces",
    icon: "Sun",
    description: "Creating beautiful and functional outdoor environments.",
    features: ["Decks and patios", "Outdoor kitchens", "Landscaping"],
    benefits: [
      "Extended living area",
      "Enhanced outdoor enjoyment",
      "Increased home value",
    ],
    expertise: 88,
    projects: 160,
    testimonial: {
      text: "Our new deck and patio have transformed our backyard. We love it!",
      author: "Nick & Amanda Evans",
    },
    rating: 4.83,
    completionTime: "3-6 months",
    priceRange: "$20k - $150k",
  },
  {
    id: "historic_restoration",
    title: "Historic Home Restoration",
    icon: "Clock",
    description: "Preserving and restoring the charm of historic homes.",
    features: [
      "Authentic materials",
      "Period-appropriate designs",
      "Modern updates",
    ],
    benefits: ["Preserved history", "Enhanced value", "Modern comfort"],
    expertise: 97,
    projects: 80,
    testimonial: {
      text: "Our historic home looks as stunning as ever, with modern amenities!",
      author: "Alice & Robert Green",
    },
    rating: 4.92,
    completionTime: "8-18 months",
    priceRange: "$200k - $2M",
  },
  {
    id: "tiny_homes",
    title: "Tiny Homes",
    icon: "Box",
    description: "Maximizing space and functionality in compact designs.",
    features: [
      "Efficient layouts",
      "Multifunctional furniture",
      "Sustainable materials",
    ],
    benefits: [
      "Affordable living",
      "Minimalistic lifestyle",
      "Lower environmental impact",
    ],
    expertise: 85,
    projects: 140,
    testimonial: {
      text: "Our tiny home is perfect for our minimalist lifestyle. Thank you!",
      author: "Jenna & Matt Carter",
    },
    rating: 4.75,
    completionTime: "3-6 months",
    priceRange: "$50k - $200k",
  },
  {
    id: "vacation_homes",
    title: "Vacation Homes",
    icon: "PalmTree",
    description: "Building serene retreats for relaxation and leisure.",
    features: ["Scenic locations", "Luxury amenities", "Customized designs"],
    benefits: [
      "Perfect getaway",
      "Investment potential",
      "Comfort and relaxation",
    ],
    expertise: 94,
    projects: 90,
    testimonial: {
      text: "Our vacation home is our favorite place to escape. It's perfect!",
      author: "Lisa & Mark Davis",
    },
    rating: 4.88,
    completionTime: "6-12 months",
    priceRange: "$400k - $2.5M",
  },
  {
    id: "multi_family",
    title: "Multi-Family Homes",
    icon: "Building",
    description:
      "Designing and constructing efficient multi-family residences.",
    features: ["Shared amenities", "Individual units", "Durable construction"],
    benefits: [
      "High rental income",
      "Efficient use of land",
      "Community living",
    ],
    expertise: 89,
    projects: 130,
    testimonial: {
      text: "Our multi-family property is fully occupied and generating great income!",
      author: "Tom & Karen Smith",
    },
    rating: 4.82,
    completionTime: "10-18 months",
    priceRange: "$500k - $3M",
  },
  {
    id: "modular_homes",
    title: "Modular Homes",
    icon: "Cube",
    description: "Building high-quality homes with modular efficiency.",
    features: [
      "Prefabricated modules",
      "Quick assembly",
      "Customizable designs",
    ],
    benefits: ["Faster build time", "Cost-effective", "High quality"],
    expertise: 87,
    projects: 110,
    testimonial: {
      text: "Our modular home was built quickly and is exactly what we wanted!",
      author: "Hannah & Jason Lee",
    },
    rating: 4.76,
    completionTime: "4-8 months",
    priceRange: "$150k - $800k",
  },
]

export const values = [
  { icon: CheckCircle, text: "Unwavering integrity in every project" },
  { icon: Leaf, text: "Pioneering sustainable construction practices" },
  { icon: Zap, text: "Cutting-edge innovation in building techniques" },
  { icon: Building, text: "Architectural excellence that inspires" },
  { icon: Users, text: "Client-centric approach in all we do" },
  { icon: Shield, text: "Rigorous safety standards at every step" },
]

export const principles = [
  {
    icon: Zap,
    text: "Integrating cutting-edge technology like AI and IoT for smarter, more efficient buildings",
  },
  {
    icon: Leaf,
    text: "Prioritizing renewable materials and energy-efficient designs in every project",
  },
  {
    icon: Users,
    text: "Fostering collaboration between architects, engineers, and sustainability experts",
  },
  {
    icon: Building,
    text: "Engaging with communities to ensure our projects meet local needs and enhance quality of life",
  },
  {
    icon: CheckCircle,
    text: "Continuous innovation in construction methods to reduce waste and improve efficiency",
  },
]

export const projects = [
  {
    name: "EcoTower: Green Skyscraper",
    image:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "A 50-story LEED Platinum certified office complex featuring vertical gardens, solar façades, and a revolutionary greywater recycling system.",
  },
  {
    name: "SmartLiving Residences",
    image:
      "https://images.unsplash.com/photo-1705581284827-5e6fc7c79a31?q=80&w=3489&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Luxury smart-home enabled apartments with AI-integrated systems, energy-efficient designs, and community-focused amenities.",
  },
  {
    name: "Nova Art Center",
    image:
      "https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=3774&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "A state-of-the-art cultural hub featuring adaptive reuse of a historic factory, with cutting-edge acoustics and flexible exhibition spaces.",
  },
  {
    name: "Quantum Research Facility",
    image:
      "https://images.unsplash.com/photo-1473876637954-4b493d59fd97?q=80&w=3792&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Next-generation laboratories and collaborative spaces designed for breakthrough scientific research, featuring vibration-controlled environments and adaptive workspaces.",
  },
]

export const team = [
  {
    name: "Dr. Amelia Richardson",
    position: "CEO & Founder",
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "With over 20 years of experience in sustainable architecture and urban planning, Dr. Richardson has led ConstructCo to become an industry leader in eco-friendly building solutions.",
  },
  {
    name: "Marcus Chen",
    position: "Chief Architect",
    image:
      "https://plus.unsplash.com/premium_photo-1664301610794-4da239a50629?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "A visionary designer with a passion for blending functionality with aesthetic beauty, Marcus has won numerous international awards for his innovative architectural concepts.",
  },
  {
    name: "Dr. Emily Okonkwo",
    position: "Head of Sustainability",
    image:
      "https://images.unsplash.com/photo-1489980557514-251d61e3eeb6?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "With a Ph.D. in Environmental Engineering, Emily spearheads our initiatives in renewable energy integration and zero-waste construction methodologies.",
  },
  {
    name: "Robert Tanaka",
    position: "Chief Innovation Officer",
    image:
      "https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?q=80&w=3876&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "Robert leads our R&D team, focusing on integrating AI, IoT, and robotics into construction processes to enhance efficiency and safety.",
  },
]
